export const fileArr = [
  '1.txt',
  '2.txt',
  '3.txt',
  '4.txt',
  '5.txt',
  '6.txt',
  '7.txt',
  '8.txt',
  '9.txt',
  '10.txt',
  '11.txt',
  '12.txt',
  '13.txt',
  '14.txt',
  '15.txt',
  '16.txt',
  '17.txt',
  '18.txt',
  '19.txt',
  '20.txt',
  '21.txt',
  '22.txt',
];

export const stopWords = [
  'a',
  'is',
  'the',
  'of',
  'all',
  'and',
  'to',
  'can',
  'be',
  'as',
  'once',
  'for',
  'at',
  'am',
  'are',
  'has',
  'have',
  'had',
  'up',
  'his',
  'her',
  'in',
  'on',
  'no',
  'we',
  'do',
];

export const testArr = [
  { fileName: './ResearchPapers/1.txt', docID: 1 },
  { fileName: './ResearchPapers/2.txt', docID: 2 },
  { fileName: './ResearchPapers/3.txt', docID: 3 },
  { fileName: './ResearchPapers/7.txt', docID: 7},
  { fileName: './ResearchPapers/8.txt', docID: 8},
  { fileName: './ResearchPapers/9.txt', docID: 9},
  { fileName: './ResearchPapers/11.txt', docID: 11 },
  { fileName: './ResearchPapers/12.txt', docID: 12},
  { fileName: './ResearchPapers/13.txt', docID: 13 },
  { fileName: './ResearchPapers/14.txt', docID: 14 },
  { fileName: './ResearchPapers/15.txt', docID: 15 },
  { fileName: './ResearchPapers/16.txt', docID: 16 },
  { fileName: './ResearchPapers/17.txt', docID: 17 },
  { fileName: './ResearchPapers/18.txt', docID: 18 },
  { fileName: './ResearchPapers/21.txt', docID: 21 },
  { fileName: './ResearchPapers/22.txt', docID: 22 },
  { fileName: './ResearchPapers/23.txt', docID: 23 },
  { fileName: './ResearchPapers/24.txt', docID: 24 },
  { fileName: './ResearchPapers/25.txt', docID: 25 },
  { fileName: './ResearchPapers/26.txt', docID: 26},
];
